# Generated by Django 5.0.3 on 2024-05-24 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_remove_order_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReserveResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=13)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "table",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.table"
                    ),
                ),
            ],
        ),
    ]
